/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dc' at '7/2/16 11:43 PM' with Gradle 2.14
 *
 * @author dc, @date 7/2/16 11:43 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
