package com.example;

import java.io.File;

import org.apache.avro.file.DataFileReader;
import org.apache.avro.file.DataFileWriter;
import org.apache.avro.io.DatumReader;
import org.apache.avro.io.DatumWriter;
import org.apache.avro.specific.SpecificDatumReader;
import org.apache.avro.specific.SpecificDatumWriter;

import com.example.avroSample.model.Automobile;

/**
 * Hello world!
 *
 */
public class App 
{
    public static void main( String[] args )
    {
      System.out.println( "Hello World!" );

//3 different way  to use the autogenerated code from the apache avro webpage
//1) use default ctor and call the setters/getters
Automobile autoDefault = new Automobile();
autoDefault.setModelName("toyota");
autoDefault.setMake("prius");
autoDefault.setModelYear(2014);
autoDefault.setPassengerCapacity(5);
System.out.println("auto1:"+ autoDefault.getModelName()+" make:"+autoDefault.getMake()+" modelYear:"+autoDefault.getModelYear()+" pc:"+autoDefault.getPassengerCapacity() );

//2 ) use autogenerated code to create an Automobile object. 
Automobile auto1 = new Automobile("tesla","models",2014,5);
System.out.println("auto1:"+ auto1.getModelName()+" make:"+auto1.getMake()+" modelYear:"+auto1.getModelYear()+" pc:"+auto1.getPassengerCapacity() );
 

      //create objects based on avro schema
      Automobile auto = Automobile.newBuilder().setMake("speedy car")
      .setModelName("automobile").setModelYear(2013).setPassengerCapacity(2).build();

      DatumWriter<Automobile> datumWriter = new SpecificDatumWriter<Automobile>(Automobile.class);
      DataFileWriter<Automobile> fileWriter = new DataFileWriter<Automobile>(datumWriter);

	try{
	    File outputFile = new File("/home/dc/testfile");
        fileWriter.create(auto.getSchema(),outputFile);
        fileWriter.append(auto);
        fileWriter.close();
      }catch(Exception e){
        e.printStackTrace();
      }

      //reconstruct data 
      DatumReader dr = new SpecificDatumReader<Automobile>(Automobile.class);
      try{
        File outputFile = new File("/home/dc/testfile1");
		DataFileReader<Automobile> fileReader = new DataFileReader<Automobile>(outputFile,dr);
      }catch(Exception e){
        e.getStackTrace();
      }
    }
}

