/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.example.avro;  
@SuppressWarnings("all")
/** Stores details about an email address that a user has associated with their account. */
@org.apache.avro.specific.AvroGenerated
public class EmailAddress extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EmailAddress\",\"namespace\":\"com.example.avro\",\"doc\":\"Stores details about an email address that a user has associated with their account.\",\"fields\":[{\"name\":\"address\",\"type\":\"string\",\"doc\":\"The email address, e.g. `foo@example.com`\"},{\"name\":\"verified\",\"type\":\"boolean\",\"doc\":\"true if the user has clicked the link in a confirmation email to this address.\",\"default\":false},{\"name\":\"dateAdded\",\"type\":\"long\",\"doc\":\"Timestamp (milliseconds since epoch) when the email address was added to the account.\"},{\"name\":\"dateBounced\",\"type\":[\"null\",\"long\"],\"doc\":\"Timestamp (milliseconds since epoch) when an email sent to this address last bounced. Reset to null when the address no longer bounces.\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** The email address, e.g. `foo@example.com` */
  @Deprecated public java.lang.CharSequence address;
  /** true if the user has clicked the link in a confirmation email to this address. */
  @Deprecated public boolean verified;
  /** Timestamp (milliseconds since epoch) when the email address was added to the account. */
  @Deprecated public long dateAdded;
  /** Timestamp (milliseconds since epoch) when an email sent to this address last bounced. Reset to null when the address no longer bounces. */
  @Deprecated public java.lang.Long dateBounced;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public EmailAddress() {}

  /**
   * All-args constructor.
   */
  public EmailAddress(java.lang.CharSequence address, java.lang.Boolean verified, java.lang.Long dateAdded, java.lang.Long dateBounced) {
    this.address = address;
    this.verified = verified;
    this.dateAdded = dateAdded;
    this.dateBounced = dateBounced;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return address;
    case 1: return verified;
    case 2: return dateAdded;
    case 3: return dateBounced;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: address = (java.lang.CharSequence)value$; break;
    case 1: verified = (java.lang.Boolean)value$; break;
    case 2: dateAdded = (java.lang.Long)value$; break;
    case 3: dateBounced = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'address' field.
   * The email address, e.g. `foo@example.com`   */
  public java.lang.CharSequence getAddress() {
    return address;
  }

  /**
   * Sets the value of the 'address' field.
   * The email address, e.g. `foo@example.com`   * @param value the value to set.
   */
  public void setAddress(java.lang.CharSequence value) {
    this.address = value;
  }

  /**
   * Gets the value of the 'verified' field.
   * true if the user has clicked the link in a confirmation email to this address.   */
  public java.lang.Boolean getVerified() {
    return verified;
  }

  /**
   * Sets the value of the 'verified' field.
   * true if the user has clicked the link in a confirmation email to this address.   * @param value the value to set.
   */
  public void setVerified(java.lang.Boolean value) {
    this.verified = value;
  }

  /**
   * Gets the value of the 'dateAdded' field.
   * Timestamp (milliseconds since epoch) when the email address was added to the account.   */
  public java.lang.Long getDateAdded() {
    return dateAdded;
  }

  /**
   * Sets the value of the 'dateAdded' field.
   * Timestamp (milliseconds since epoch) when the email address was added to the account.   * @param value the value to set.
   */
  public void setDateAdded(java.lang.Long value) {
    this.dateAdded = value;
  }

  /**
   * Gets the value of the 'dateBounced' field.
   * Timestamp (milliseconds since epoch) when an email sent to this address last bounced. Reset to null when the address no longer bounces.   */
  public java.lang.Long getDateBounced() {
    return dateBounced;
  }

  /**
   * Sets the value of the 'dateBounced' field.
   * Timestamp (milliseconds since epoch) when an email sent to this address last bounced. Reset to null when the address no longer bounces.   * @param value the value to set.
   */
  public void setDateBounced(java.lang.Long value) {
    this.dateBounced = value;
  }

  /** Creates a new EmailAddress RecordBuilder */
  public static com.example.avro.EmailAddress.Builder newBuilder() {
    return new com.example.avro.EmailAddress.Builder();
  }
  
  /** Creates a new EmailAddress RecordBuilder by copying an existing Builder */
  public static com.example.avro.EmailAddress.Builder newBuilder(com.example.avro.EmailAddress.Builder other) {
    return new com.example.avro.EmailAddress.Builder(other);
  }
  
  /** Creates a new EmailAddress RecordBuilder by copying an existing EmailAddress instance */
  public static com.example.avro.EmailAddress.Builder newBuilder(com.example.avro.EmailAddress other) {
    return new com.example.avro.EmailAddress.Builder(other);
  }
  
  /**
   * RecordBuilder for EmailAddress instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EmailAddress>
    implements org.apache.avro.data.RecordBuilder<EmailAddress> {

    private java.lang.CharSequence address;
    private boolean verified;
    private long dateAdded;
    private java.lang.Long dateBounced;

    /** Creates a new Builder */
    private Builder() {
      super(com.example.avro.EmailAddress.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.example.avro.EmailAddress.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.address)) {
        this.address = data().deepCopy(fields()[0].schema(), other.address);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.verified)) {
        this.verified = data().deepCopy(fields()[1].schema(), other.verified);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.dateAdded)) {
        this.dateAdded = data().deepCopy(fields()[2].schema(), other.dateAdded);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.dateBounced)) {
        this.dateBounced = data().deepCopy(fields()[3].schema(), other.dateBounced);
        fieldSetFlags()[3] = true;
      }
    }
    
    /** Creates a Builder by copying an existing EmailAddress instance */
    private Builder(com.example.avro.EmailAddress other) {
            super(com.example.avro.EmailAddress.SCHEMA$);
      if (isValidValue(fields()[0], other.address)) {
        this.address = data().deepCopy(fields()[0].schema(), other.address);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.verified)) {
        this.verified = data().deepCopy(fields()[1].schema(), other.verified);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.dateAdded)) {
        this.dateAdded = data().deepCopy(fields()[2].schema(), other.dateAdded);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.dateBounced)) {
        this.dateBounced = data().deepCopy(fields()[3].schema(), other.dateBounced);
        fieldSetFlags()[3] = true;
      }
    }

    /** Gets the value of the 'address' field */
    public java.lang.CharSequence getAddress() {
      return address;
    }
    
    /** Sets the value of the 'address' field */
    public com.example.avro.EmailAddress.Builder setAddress(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.address = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'address' field has been set */
    public boolean hasAddress() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'address' field */
    public com.example.avro.EmailAddress.Builder clearAddress() {
      address = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'verified' field */
    public java.lang.Boolean getVerified() {
      return verified;
    }
    
    /** Sets the value of the 'verified' field */
    public com.example.avro.EmailAddress.Builder setVerified(boolean value) {
      validate(fields()[1], value);
      this.verified = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'verified' field has been set */
    public boolean hasVerified() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'verified' field */
    public com.example.avro.EmailAddress.Builder clearVerified() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'dateAdded' field */
    public java.lang.Long getDateAdded() {
      return dateAdded;
    }
    
    /** Sets the value of the 'dateAdded' field */
    public com.example.avro.EmailAddress.Builder setDateAdded(long value) {
      validate(fields()[2], value);
      this.dateAdded = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'dateAdded' field has been set */
    public boolean hasDateAdded() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'dateAdded' field */
    public com.example.avro.EmailAddress.Builder clearDateAdded() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'dateBounced' field */
    public java.lang.Long getDateBounced() {
      return dateBounced;
    }
    
    /** Sets the value of the 'dateBounced' field */
    public com.example.avro.EmailAddress.Builder setDateBounced(java.lang.Long value) {
      validate(fields()[3], value);
      this.dateBounced = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'dateBounced' field has been set */
    public boolean hasDateBounced() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'dateBounced' field */
    public com.example.avro.EmailAddress.Builder clearDateBounced() {
      dateBounced = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public EmailAddress build() {
      try {
        EmailAddress record = new EmailAddress();
        record.address = fieldSetFlags()[0] ? this.address : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.verified = fieldSetFlags()[1] ? this.verified : (java.lang.Boolean) defaultValue(fields()[1]);
        record.dateAdded = fieldSetFlags()[2] ? this.dateAdded : (java.lang.Long) defaultValue(fields()[2]);
        record.dateBounced = fieldSetFlags()[3] ? this.dateBounced : (java.lang.Long) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
