/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.example.avro;  
@SuppressWarnings("all")
/** * `PENDING`: the user has started authorizing, but not yet finished
* `ACTIVE`: the token should work
* `DENIED`: the user declined the authorization
* `EXPIRED`: the token used to work, but now it doesn't
* `REVOKED`: the user has explicitly revoked the token */
@org.apache.avro.specific.AvroGenerated
public enum OAuthStatus { 
  PENDING, ACTIVE, DENIED, EXPIRED, REVOKED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OAuthStatus\",\"namespace\":\"com.example.avro\",\"doc\":\"* `PENDING`: the user has started authorizing, but not yet finished\\n* `ACTIVE`: the token should work\\n* `DENIED`: the user declined the authorization\\n* `EXPIRED`: the token used to work, but now it doesn't\\n* `REVOKED`: the user has explicitly revoked the token\",\"symbols\":[\"PENDING\",\"ACTIVE\",\"DENIED\",\"EXPIRED\",\"REVOKED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
