/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.example.avro;  
@SuppressWarnings("all")
/** * `HIDDEN`: not currently visible, e.g. because it becomes actionable in future
* `ACTIONABLE`: appears in the current to-do list
* `DONE`: marked as done, but still appears in the list
* `ARCHIVED`: marked as done and no longer visible
* `DELETED`: not done and removed from list (preserved for undo purposes) */
@org.apache.avro.specific.AvroGenerated
public enum ToDoStatus { 
  HIDDEN, ACTIONABLE, DONE, ARCHIVED, DELETED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ToDoStatus\",\"namespace\":\"com.example.avro\",\"doc\":\"* `HIDDEN`: not currently visible, e.g. because it becomes actionable in future\\n* `ACTIONABLE`: appears in the current to-do list\\n* `DONE`: marked as done, but still appears in the list\\n* `ARCHIVED`: marked as done and no longer visible\\n* `DELETED`: not done and removed from list (preserved for undo purposes)\",\"symbols\":[\"HIDDEN\",\"ACTIONABLE\",\"DONE\",\"ARCHIVED\",\"DELETED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
