/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.example;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum PrivacyType { 
  FRIENDS, FRIENDS_OF_FRIENDS, PUBLIC, CUSTOM  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PrivacyType\",\"namespace\":\"com.example\",\"symbols\":[\"FRIENDS\",\"FRIENDS_OF_FRIENDS\",\"PUBLIC\",\"CUSTOM\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
