/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.example;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface Social {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Social\",\"namespace\":\"com.example\",\"types\":[{\"type\":\"enum\",\"name\":\"PrivacyType\",\"symbols\":[\"FRIENDS\",\"FRIENDS_OF_FRIENDS\",\"PUBLIC\",\"CUSTOM\"]},{\"type\":\"record\",\"name\":\"Person\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"year_of_birth\",\"type\":\"int\"},{\"name\":\"country\",\"type\":\"string\",\"default\":\"US\"},{\"name\":\"state\",\"type\":\"string\"},{\"name\":\"friends\",\"type\":{\"type\":\"array\",\"items\":\"Person\"},\"default\":[]},{\"name\":\"languages\",\"type\":{\"type\":\"array\",\"items\":\"string\"},\"default\":[\"English\",\"Java\"]},{\"name\":\"defaultPrivacy\",\"type\":\"PrivacyType\",\"default\":\"FRIENDS\"}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends Social {
    public static final org.apache.avro.Protocol PROTOCOL = com.example.Social.PROTOCOL;
  }
}