/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.zenfractal;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface SparkParquetAvro {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"SparkParquetAvro\",\"namespace\":\"com.zenfractal\",\"types\":[{\"type\":\"enum\",\"name\":\"AminoAcidType\",\"symbols\":[\"ALIPHATIC\",\"HYDROXYL\",\"CYCLIC\",\"AROMATIC\",\"BASIC\",\"ACIDIC\"]},{\"type\":\"record\",\"name\":\"AminoAcid\",\"fields\":[{\"name\":\"type\",\"type\":\"AminoAcidType\"},{\"name\":\"fullName\",\"type\":\"string\"},{\"name\":\"abbreviation\",\"type\":\"string\"},{\"name\":\"molecularWeight\",\"type\":\"float\"}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends SparkParquetAvro {
    public static final org.apache.avro.Protocol PROTOCOL = com.zenfractal.SparkParquetAvro.PROTOCOL;
  }
}